language: swift
osx_image: xcode10.2
xcode_workspace: station.xcworkspace
xcode_scheme: station
script:
  - xcodebuild clean build -sdk iphonesimulator -workspace station.xcworkspace -scheme station CODE_SIGNING_REQUIRED=NO | xcpretty
branches:
  only:
  - master
before_install:
  - rvm use system
  - gem install xcpretty
  - sudo gem install cocoapods 
  - pod repo update
